### ISSUE TITLE
Import library problem

### ISSUE THREAD

**Issue by tsenggordon** [nupic-community/nupic.vision#1]
Hi James:
  I'm a student from Taiwan. I'm working on building a image (object)/ video (action) recognition system based on NUPIC. It's difficult to me as a newbee for deep learning and python also. Then, I find your nupic.vision project on git. It's very useful for me. But I encounter some problems:

1. I don't have reference library "classifiers" class exactMatch. Can you give me some hints to install it?

2. It seems in this demo project that only one-dimensional spatial pooler is used, so is there any ways to use multi-dimensional SP, or do I have to implement it by myself?

Thanks a lot for help.

BR.

Gordon

**Comment by breznak** [comment]
@tsenggordon how did your work on CLA+vision turn out? I'm just starting in the domain too.
