### ISSUE TITLE
Wiki: Research paper organization

### ISSUE THREAD

**Issue by rcrowder** [nupic-community/nupic.vision#10]
I'm gathering together more vision related research paper links for the Wiki page [1].

- How do we organize the sections and sub-sections? Break down simply via Cortical processing and Sub-cortical processing? Separate bio-mimetic and bio-inspired?
- What is the best way to link to papers? DOI links and direct PDF links for non-released papers? (such as [2])
- Promote Mendeley and create a Nupic.vision group?

Note, link [2] is an extreme example of a situation where the paper hosting serve is internal to an institution, and likely to change at some point in the future.

1 https://github.com/nupic-community/nupic.vision/wiki/Neural-Nets-&-Vision-related-papers
2 http://klab.smpp.northwestern.edu/wiki/images/c/c9/Kording_2006_Causal_infer_sensorimotor_integrate.pdf

**Comment by rcrowder** [comment]
I've started adding papers to the wiki page. @breznak Be good to hear whether this is the right way to outline each paper?

https://github.com/nupic-community/nupic.vision/wiki/Neural-Nets-&-Vision-related-papers

**Comment by breznak** [comment]
@rcrowder thanks for your work! :+1: I like your detailed info about the papers, and you supplied me with some nice reading for upcoming evenings :grinning: 

(just a nit, the links in menu need some love)

**Comment by breznak** [comment]
we should probably consolidate (and promote) this wiki from "main nupic" wiki. CC @rhyolight

**Comment by rcrowder** [comment]
@breznak Thanks. After a year with a nose almost constantly in research papers and books, there's lots more that could be added. But the ones I've thrown in there so far should give a good indication of what can be done to implement vision pre-processing for the HTM, and starting points for investigating subjects further.
I was going to outline my own work here, but threw a reply to your Neuromorphic ML post. I'm hoping before the hackathon to have TM and some audio example ready (probably in a new nupic.community repo for audio).

**Comment by breznak** [comment]
@rcrowder I was also thinking about starting nupic.nlp & nupic.audio for
some of my projects, so let's do this!

**Comment by rcrowder** [comment]
@breznak CC @rhyolight
Sounds great. I'll have a think this long UK holiday weekend about the audio repo. Although I may be biased requiring analog, possibly considering a midi repo for anything digital. I wish FLIR cameras [1] weren't so expensive (SPI based, $350 each @Sparkfun.com [2]), have to stick with CIF resolution RGB streams (OV6620 CMOS sensor), or laptop reduced video stream.

Putting the paper abstracts bloats out the wiki page. But, it does show a flow of relevant information, keywords, and techniques (such as log gabors). Maybe going a step too far initially, but imo a good indication of potential work and knowledge to share.

Closing this issue off, in favor of raising another issue to deal with web paper URI links. 

1 http://www.ece.ucsb.edu/academics/undergrad/capstone/documents-2014/ir-scout-poster.pdf
2 https://www.sparkfun.com/products/13233

**Comment by rhyolight** [comment]
Nice work!
